// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SGQP.Data.Contexts;
using System;

namespace SGQP.Data.Migrations
{
    [DbContext(typeof(DefaultContext))]
    [Migration("20180626024137_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SGQP.Domain.Entities.Discipline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("SGQP.Domain.Entities.QuestionAlternative", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("QuestionAlternatives");
                });

            modelBuilder.Entity("SGQP.Domain.Entities.QuestionDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cod");

                    b.Property<string>("Content");

                    b.Property<DateTime>("DataUsed");

                    b.HasKey("Id");

                    b.ToTable("QuestionDescriptions");
                });

            modelBuilder.Entity("SGQP.Domain.Entities.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("SGQP.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int?>("PasswordId");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("PasswordId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SGQP.Domain.ValueObjects.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.HasKey("Id");

                    b.ToTable("Password");
                });

            modelBuilder.Entity("SGQP.Domain.Entities.User", b =>
                {
                    b.HasOne("SGQP.Domain.ValueObjects.Password", "Password")
                        .WithMany()
                        .HasForeignKey("PasswordId");
                });
#pragma warning restore 612, 618
        }
    }
}
